### ISSUE TITLE
Remove Shorts from the home feed

### ISSUE THREAD

**Issue by Anshul-004** [GDGC-MET/Detoxify-Youtube#1]
**Is your feature request related to a problem? Please describe.**
Youtube pushes shorts more on homepage , which defies the purpose of focusing, so shorts must be eliminated from the homepage

**Describe the solution you'd like**
Remove shorts in entirety from the homepage.

**Describe alternatives you've considered**
To blur the shorts but, it still distracts once got init.

**Comment by aniketnal** [comment]
Good issue, work on it
