### ISSUE TITLE
Tile unfocus time is too short

### ISSUE THREAD

**Issue by Anshul-004** [GDGC-MET/Detoxify-Youtube#2]
**Describe the bug**
video tile is unfocused as soon as cursor is hovered over, defying the purpose of the extension.

**To Reproduce**
1. Go to youtube
2. Hover on any blurred video tile
3. video is unfocused without any delay, which may also be the result of unintended hovering

**Expected behavior**
Video tile must be unfocused after atleast 1-2 seconds of hovering

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome

**Comment by aniketnal** [comment]
All good, Work on this
