### ISSUE TITLE
Not able to hide Shorts

### ISSUE THREAD

**Issue by AtharvaBhusnale** [GDGC-MET/Detoxify-Youtube#4]
The Extension is not able to hide the shorts form the youtube rathers shows all the shorts it just shows all the shorts irrespective of the keyword searched 
-> extention to be able to hide the shorts 
![Screenshot 2024-10-14 140732](https://github.com/user-attachments/assets/6e00bf54-e979-471f-bb4c-7699f03c3b48)

**Comment by cubaseuser123** [comment]
issue already present
