### ISSUE TITLE
blur feed

### ISSUE THREAD

**Issue by vaishnavis31** [GDGC-MET/Detoxify-Youtube#7]
the suggestion in the feed is blur and thumbnails and titles are not visible unable to understand the content

**Comment by aniketnal** [comment]
@vaishnavis31 Please read readme.md and then try to solve the issues.

**Comment by aniketnal** [comment]
the extension is all about hiding the irrelevant videos in your feed. you will have to mention comma seperarted values in inout which will show only those videos to you
